### ISSUE TITLE
hbmenu `author` and `version` tags unspecified

### ISSUE THREAD

**Issue by techniponi** [RSDuck/vba-next-switch#10]
They show up as "`Unspecified Author`" and "`1.0.0`" on all releases, presumably due to undefined metadata.

(Pictured: Release 0.4)

![2018052719475800-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/4731368/40592728-2da43f74-61e8-11e8-9324-e1c5518b8daf.jpg)

**Comment by dene-** [comment]
It's fixed on my pull request, but I'm not sure what to put on author. It is _RSDuck_ for now.
