### ISSUE TITLE
Live sram saving?

### ISSUE THREAD

**Issue by fennectech** [RSDuck/vba-next-switch#24]
Does vba-next write the ‘battery file’ the moment it is altered. Or when you enter the menu.

**Comment by jakibaki** [comment]
Vba-next writes the battery-file 60 frames after the battery-memory was last written to by the game.

**Comment by fennectech** [comment]
So about one second?

**Comment by fennectech** [comment]
Thanks for the port friend.   I keep it on my switch and its the first enjoyable gba emulator for switch.  I’d love to see more features tho.
