### ISSUE TITLE
SX OS Support

### ISSUE THREAD

**Issue by xne0n** [RSDuck/vba-next-switch#27]
Hi,
I've experience some issue while trying to load roms on your awesome emulator, in SX OS 1.0 on 5.1.0.
Basically when I load any roms I get a black screen with some random colored pixels at the top and when I press the x button to exit, the whole system freezes and I have to power off the switch and restart all over...
Any idea ?

Thank you for your awesome work !
xne0n

**Comment by dene-** [comment]
They need to improve the support for homebrew, not us. Meanwhile they fix their stuff on next SX OS versions you can use VBA Next on Hekate.

Also any of us have or will have SX OS so we can't give support on that unfortunately.

Sorry though! :(

**Comment by xne0n** [comment]
Ok thanks for your quick respond, I will do that. But you know SX OS is free for homebrew ? you can download it at https://sx.xecuter.com/ . I've choose it for it's ease of use but I guess you can't have your cake and eat it too... ;-)

**Comment by RSDuck** [comment]
the new versions of SX OS fix this problem
