### ISSUE TITLE
Audio crackles on all games (release 0.2, hbmenu 2.0.0, hekate_ctcaer_1.5.1.bin, 5.0.2)

### ISSUE THREAD

**Issue by techniponi** [RSDuck/vba-next-switch#3]
I have tried:
* Super Mario Advance
* Super Mario Advance 2
* Super Mario Advance 3
* Pokémon: Emerald Version
* Goomba Color
* Pokémon Mystery Dungeon: Red Rescue Team

On all of the above titles, the game runs at full speed but the audio is very crackly and unpleasant. Everything else appears functional. Changing frameskip does not fix the audio.

Switch version 5.0.2, CFW payload `hekate_ctcaer_1.5.1.bin`, hbmenu v2.0.0, VBA-Next-Switch release 0.2.

**Comment by gotwig** [comment]
maybe add an option to use original gba bios?

**Comment by RSDuck** [comment]
> I have the gba bios in switch directory (gba_bios.bin) and I have no audio issues at all in some of the listed games. maybe try that? I run switch at fw 4.0
Loading a bios from file is currently not supported. So this is probably not the reason why the audio is fine on your system😄 

The whole problem was a bit weird, it varied widely, some people experienced it, some people didn't. I already made a fix, which fixed it for most people, it will be included in the next release, so stay tuned!

**Comment by RSDuck** [comment]
should be fixed by now

**Comment by techniponi** [comment]
Running great now (also updated `hekate_ctcaer` to `1.6` if it matters).
Thanks for all the work you're putting into this <3
