### ISSUE TITLE
Error 0x4A8 (2168-0002). Help required =)

### ISSUE THREAD

**Issue by SigfridoGaming** [RSDuck/vba-next-switch#37]
Hello there, today I wanted to use a Game Boy Advance emulator "VBA-Next" I followed a tutorial and all seemed fine until i got to the booting part, when I tried to boot it up it crashed, and i thought it was ok, I tried again and it still crashed, then i tried to boot it up with the "Album Version" of the homebrew menu (Before I used to open a game and hold R) and it gave me the crash error, I tried deleting the Atmosphere folder from my SD card but it still gave me the error. Have you got some tip to fix this problem? Thanks in advance =)

Here is the crash report
[01678480665_010000000000100d.log](https://github.com/RSDuck/vba-next-switch/files/10945997/01678480665_010000000000100d.log)

**Comment by RSDuck** [comment]
use mgba

**Comment by SigfridoGaming** [comment]
> use mgba

And... how do i download it if I may ask? Tried downloading and dropping but it didnt work ;/

**Comment by RSDuck** [comment]
http://mgba.io/downloads.html

describe not working

**Comment by SigfridoGaming** [comment]
> http://mgba.io/downloads.html
> 
> describe not working

Oops, sorry it works just fine! It was my bad for deleting the Homebrew on accident, thanks again =)
